# Generated by Django 2.2.24 on 2021-08-17 23:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20210817_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='published_date',
        ),
        migrations.AddField(
            model_name='entry',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 17, 23, 40, 31, 884046, tzinfo=utc), null=True),
        ),
    ]
