# Generated by Django 2.2.24 on 2021-08-17 23:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20210817_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 17, 23, 43, 11, 783776, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 17, 23, 43, 11, 783729, tzinfo=utc), null=True),
        ),
    ]
